// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// backpropagate_laplacian_to_conductance
arma::vec backpropagate_laplacian_to_conductance(const arma::mat& tGl, const arma::mat& tGr, const arma::umat& tadj);
RcppExport SEXP _radish2_backpropagate_laplacian_to_conductance(SEXP tGlSEXP, SEXP tGrSEXP, SEXP tadjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type tGl(tGlSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tGr(tGrSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type tadj(tadjSEXP);
    rcpp_result_gen = Rcpp::wrap(backpropagate_laplacian_to_conductance(tGl, tGr, tadj));
    return rcpp_result_gen;
END_RCPP
}
// backpropagate_conductance_to_laplacian
arma::sp_mat backpropagate_conductance_to_laplacian(const arma::vec& dgrad__ddl_dC, const arma::umat& tadj);
RcppExport SEXP _radish2_backpropagate_conductance_to_laplacian(SEXP dgrad__ddl_dCSEXP, SEXP tadjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type dgrad__ddl_dC(dgrad__ddl_dCSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type tadj(tadjSEXP);
    rcpp_result_gen = Rcpp::wrap(backpropagate_conductance_to_laplacian(dgrad__ddl_dC, tadj));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_radish2_backpropagate_laplacian_to_conductance", (DL_FUNC) &_radish2_backpropagate_laplacian_to_conductance, 3},
    {"_radish2_backpropagate_conductance_to_laplacian", (DL_FUNC) &_radish2_backpropagate_conductance_to_laplacian, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_radish2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
